language: go
dist: trusty
sudo: false

env:
  - HUGO_VERSION=0.41

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.deb
  - apt install -y hugo_$HUGO_VERSION_Linux-64bit.deb

script:
  - hugo version
  - hugo -v

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  project-name: poyo_web
  on:
    branch: master



